name: lines-of-code

on: pull_request

jobs:
  count:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: count with tokei
      uses: docker://mbologna/docker-tokei
      with:
        entrypoint: tokei
        args: -t=Zsh
