name: lines-of-code

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: count with tokei
      uses: docker://mbologna/docker-tokei
      run: |
        ls
        echo $PWD
        tokei -t=Zsh | grep '^ Zsh' | awk '{print $4 " lines of zsh"}'
